"""Add homework table and relationship

Revision ID: 249105584e94
Revises: 78cfbfb3be4f
Create Date: 2025-09-09 19:52:26.647735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249105584e94'
down_revision: Union[str, Sequence[str], None] = '78cfbfb3be4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_homework_lesson_source_id'), 'homework', ['lesson_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_lesson_source_id'), table_name='homework')
    # ### end Alembic commands ###
