"""Add schedule models

Revision ID: 2f241949a877
Revises: 838fa63694ed
Create Date: 2025-09-09 11:24:09.496477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f241949a877'
down_revision: Union[str, Sequence[str], None] = '838fa63694ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditories',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditories_id'), 'auditories', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('real_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutors_id'), 'tutors', ['id'], unique=False)
    op.create_index(op.f('ix_tutors_name'), 'tutors', ['name'], unique=False)
    op.create_table('lessons',
    sa.Column('source_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.Integer(), nullable=False),
    sa.Column('subgroup_name', sa.String(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('lesson_type', sa.String(length=10), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('auditory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditory_id'], ['auditories.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_lessons_content_hash'), 'lessons', ['content_hash'], unique=False)
    op.create_index(op.f('ix_lessons_source_id'), 'lessons', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_source_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_content_hash'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_tutors_name'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_id'), table_name='tutors')
    op.drop_table('tutors')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_auditories_id'), table_name='auditories')
    op.drop_table('auditories')
    # ### end Alembic commands ###
