"""Add groupchat table and relationship

Revision ID: 67e706baa36b
Revises: 249105584e94
Create Date: 2025-09-09 20:57:18.360021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e706baa36b'
down_revision: Union[str, Sequence[str], None] = '249105584e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chats',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('linked_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['linked_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_group_chats_chat_id'), 'group_chats', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_chats_chat_id'), table_name='group_chats')
    op.drop_table('group_chats')
    # ### end Alembic commands ###
