"""Add is_blocked

Revision ID: 78cfbfb3be4f
Revises: 4524b73d6063
Create Date: 2025-09-09 19:46:31.533216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cfbfb3be4f'
down_revision: Union[str, Sequence[str], None] = '4524b73d6063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lesson_source_id', sa.BigInteger(), nullable=False),
    sa.Column('author_telegram_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_telegram_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['lesson_source_id'], ['lessons.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_id'), 'homework', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_id'), table_name='homework')
    op.drop_table('homework')
    # ### end Alembic commands ###
