"""Add lesson_id to lessons table

Revision ID: ffd1112da87f
Revises: 28afab65b6cb
Create Date: 2025-09-09 18:11:23.802599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd1112da87f'
down_revision: Union[str, Sequence[str], None] = '28afab65b6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lessons_lesson_id'), 'lessons', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_lesson_id'), table_name='lessons')
    op.drop_column('lessons', 'lesson_id')
    # ### end Alembic commands ###
